# Generated by Django 2.1.3 on 2018-11-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('edad', models.IntegerField(null=True)),
                ('estadoCivil', models.CharField(choices=[('s', 'Soltero'), ('c', 'Casado'), ('v', 'Viudo'), ('d', 'Divorciado')], max_length=15, null=True)),
                ('direccion', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=15, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
