# Generated by Django 2.1.3 on 2018-11-09 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20181109_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='estudiantes',
            name='estadoCivil',
        ),
    ]
